#+TITLE: Bibtex with Racket
#+AUTHOR: Pjotr Prins

* Introduction

This little program uses pandoc to output JSON for bibtex inputs. Next we transform this to html and org markdown (or is it markup?). It is written in racket+pandoc. Should move to guile some day.

* Table of Contents                                                     :TOC:
 - [[#introduction][Introduction]]
 - [[#bibtex-conv][Bibtex-conv]]
 - [[#bib-file-manipulations][Bib file manipulations]]
 - [[#install][Install]]
   - [[#using-gnu-guix][Using GNU Guix]]
 - [[#copyright][Copyright]]

* Bibtex-conv

Features:

- Generate simple output from bibtex (.bib)
- Use keyword filter

Bibtex is an extremely useful format for generating literature
references. This little program takes the JSON output generated by
[[https://github.com/jgm/pandoc-citeproc/blob/master/man/pandoc-citeproc.1.md][pandoc-citeproc]], e.g.

#+begin_src sh
pandoc-citeproc --bib2json test/data/biblio.bib | ./bin/bibtex-conv -k bio1
#+end_src

or the later

#+begin_src sh
 pandoc --to=csljson test/data/biblio.bib | racket ./bin/bibtex-conv
#+end_src

and print it out in useful ways with racket-bibtex. Use it to generate
specialised HTML references on grant proposals, biosketches, home
pages etc. In earlier days I used the Ruby bibtex parser, but with
pandoc there is no longer a need for that. E.g.

#+begin_src sh
pandoc-citeproc --bib2json biblio.bib|bibtex-conv --keyword group
#+end_src

generates Org-mode style output

#+begin_example
1. [[http://www.ncbi.nlm.nih.gov/pubmed/31278683][Scalable Workflows and
   Reproducible Data Analysis for Genomics]] by F. Strozzi, R. Janssen,
   R. Wurmus, M. R. Crusoe, G. Githinji, P. Di Tommaso, D. Belhachemi,
   S. Moller, G. Smant, J. Ligt and _P. Prins_,
   @@html:<span class="journal">@@Methods Mol Biol@@html:</span>@@
   (@@html:<span class="year">@@2019@@html:</span>@@) Vol 1910
   p. 723-745, DOI: 10.1007/978-1-4939-9074-0_24
#+end_example

which can be turned into HTML via emacs org-mode. To generate LaTeX
directly it is also possible to use the --latex switch

#+begin_src sh
pandoc --to=csljson test/data/biblio.bib | racket ./bin/bibtex-conv --keyword group --latex
#+end_src

renders

#+begin_src tex
\item Arends D, {\ul Prins P}, Jansen RC, Broman KW (2010),
  \emph{R/qtl: high-throughput multiple QTL mapping.}
  \uline{Bioinformatics}, {\bf 26}(23), 2990-2992.
#+end_src

* Bib file manipulations

Note that both [[http://gerd-neugebauer.de/software/TeX/BibTool/bibtool.pdf][bibtool]] and biber have support for manipulating bib
databases. Check those first before attempting to roll your own.

* Install

Dependencies:

1. racket
2. pandoc
3. pandoc-citeproc

** Using GNU Guix

#+begin_src sh
   guix shell -C racket ghc-pandoc ghc-citeproc
   pandoc --to=csljson test.bib
#+end_src

Generate my CV in org markdown:

: pandoc --to=csljson pjotr.bib | racket ./bin/bibtex-conv -k cv

LaTeX output:

: pandoc --to=csljson pjotr.bib | racket ./bin/bibtex-conv -k cv -l

* Copyright

Copyright (c) 2020-2022 Pjotr Prins.  This code is published under the GPL3, see [[LICENSE]] for details.
